//                              -*- Mode: Idl -*- 
// Generic_Sensor.idl --- 
// Author           : Manoj Srivastava ( srivasta@glaurung.stdc.com ) 
// Created On       : Fri Aug 17 16:06:14 2001
// Created On Node  : glaurung.stdc.com
// Last Modified By : Manoj Srivastava
// Last Modified On : Sat Dec  1 01:55:23 2001
// Last Machine Used: ember.stdc.com
// Update Count     : 11
// Status           : Unknown, Use with caution!
// HISTORY          : 
// Description      : 
// 
// 
#ifndef GENERIC_SENSOR_IDL
#define GENERIC_SENSOR_IDL


/** @file Generic_Sensor.idl
 *  @ingroup GenericSensor 
 *  @brief The implementation of a Sensor interface
 *
 *  $Id: Generic_Sensor.idl,v 1.4 2001/12/09 02:11:58 nath Exp $
 */

#include "Command.idl"

module STDC
{
  module QMS 
  {   
    module Citizen 
    {
      /**
       * This is a Generic Sensor. It is a QMS citizen, and is
       * required to expose the mandatory Corba interfaces, that will
       * enable a QMS administrator to control this Sensor causing it
       * to shutdown, pause etc. This interface is  derived from the
       * Command and Control Interface. 
       */
      interface Generic_Sensor : Command
      {
      };
    };
  };
};

#endif // GENERIC_SENSOR_IDL
